#!/bin/zsh
# Builds Nightwatch.app as a universal binary (arm64 + x86_64) or Intel-only (x86_64),
# from project.yml (generated by xcodegen), signs it ad hoc, and (on macOS 15 and later)
# can produce a signed .dmg for distribution.
#
# Usage:
#   scripts/build-intel.sh             # universal build (default)
#   scripts/build-intel.sh --intel     # Intel-only (x86_64)
#   scripts/build-intel.sh --universal # explicit universal (arm64 + x86_64)
#
# A universal/double-architecture build works from either an Apple Silicon or Intel Mac.
# On Apple Silicon this produces native arm64 plus Rosetta-translated x86_64. On Intel
# this produces native x86_64 plus Rosetta-translated arm64 (macOS 15+ can translate).
#
# Needs: Xcode 14+, brew install xcodegen. No Apple signing identity => ad hoc; the app
# runs locally but lacks the signed widget and falls back to Open-Meteo instead of WeatherKit.
set -euo pipefail
cd "$(dirname "$0")/.."   # repo root
fail() { print -u2 "build-intel: $1"; exit 1 }

xcrun --find xcodebuild >/dev/null 2>&1 || fail "Xcode is not installed"
command -v xcodegen >/dev/null || fail "xcodegen is not installed: brew install xcodegen"

PLIST=Sources/Nightwatch/Info.plist
BUNDLE_ID=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "$PLIST")
APP=build/Nightwatch.app
UNIVERSAL="${1:-}"
case "$UNIVERSAL" in
  --intel) ARCHS=(-arch x86_64);;
  --universal|--universal) ARCHS=(-arch arm64 -arch x86_64);;
  "") ARCHS=(-arch arm64 -arch x86_64);;   # default: universal
  *) fail "unrecognised option: $1 (use --intel, --universal, or none)"
esac
print "Building Nightwatch with ${ARCHS[@]:1}"

mkdir -p build; rm -rf "$APP"
xcodegen generate --quiet
PINS=Nightwatch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm
mkdir -p "$PINS" && cp Package.resolved "$PINS/"
CONDITIONS=""

# Run the build. CODE_SIGNING_ALLOWED=NO produces an ad-hoc build (no widget) so it runs
# without a team; use a signed build instead when you have an Apple Development identity.
"${ARCHS[@]}" xcodebuild -project Nightwatch.xcodeproj -scheme Nightwatch -configuration Release \
    -derivedDataPath build/xcode \
    -onlyUsePackageVersionsFromResolvedFile "SWIFT_ACTIVE_COMPILATION_CONDITIONS=$CONDITIONS" \
    MARKETING_VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleShortVersionString' "$PLIST")" \
    CURRENT_PROJECT_VERSION="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleVersion' "$PLIST")" \
    build > build/xcode.log 2>&1 || fail "the Xcode build failed: see build/xcode.log"

PRODUCT=build/xcode/Build/Products/Release/Nightwatch.app
ditto "$PRODUCT" "$APP"
rm -rf "$APP/Contents/PlugIns" "$APP/Contents/XPCServices"
# Ad-hoc entitlements (no App Group without a team -> no widget snapshot).
cat > build/Nightwatch.entitlements <<ENT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/plist-1.dtd">
<plist version="1.0"><dict>
  <key>com.apple.security.personal-information.location</key><true/>
  <key>com.apple.security.app-sandbox</key><true/>
  <key>com.apple.security.network.client</key><true/>
  <key>com.apple.security.temporary-exception.files.home-relative-path.read-only</key><array><string>/Library/Application Support/Nightwatch/</string><string>/Library/Caches/Nightwatch/</string></array>
  <key>com.apple.security.files.user-selected.read-only</key><true/>
</dict></plist>
ENT
/usr/libexec/PlistBuddy -c "Delete :NightwatchAppGroup" "$APP/Contents/Info.plist"
codesign --force --sign - --entitlements build/Nightwatch.entitlements "$APP"

print "Built $APP"
file "$APP/Contents/MacOS/Nightwatch" | cut -d: -f2- | sed 's/^ //'
print
print "Inspect:  file \"$APP/Contents/MacOS/Nightwatch\""
print "Run:      open \"$APP\""
